# Generated by Django 6.0.2 on 2026-02-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='presentations/previews/'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
