# Generated by Django 6.0.2 on 2026-02-25 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_presentation_preview_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectupdate',
            name='image',
        ),
        migrations.CreateModel(
            name='ProjectUpdateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_updates/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.projectupdate')),
            ],
        ),
    ]
