# Generated by Django 6.0.2 on 2026-02-25 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_projectupdate_image_projectupdateimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('result', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='test_cases/')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.testcaseentry')),
            ],
        ),
    ]
