# Generated by Django 6.0.2 on 2026-02-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testcaseentry_testcaseimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='git_screenshots/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GitUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Контроль версий Git', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('repository_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('screenshots', models.ManyToManyField(blank=True, related_name='git_updates', to='core.gitscreenshot')),
            ],
        ),
    ]
